### ISSUE TITLE
Request for Pcap test data.

### ISSUE THREAD

**Issue by jahagirdar** [paritytrading/nassau#75]
Hi,
I came across this repo which searching for pcap files for different exchange protocols (MoldUDP64, SoupBINTCP, ITCH, OUCH etc)
In case you have tcpdump's for these protocols can you please share them.
Regards
Vijay

**Comment by jvirtanen** [comment]
Hi @jahagirdar! No, at least I don't currently have any packet captures to share. Nasdaq has some sample files on their FTP site but I think none of them are in the pcap format:
```
ftp://emi.nasdaq.com/
```

**Comment by jahagirdar** [comment]
@jvirtanen Thanks for the response,
I downloaded one of the ITCH sample .gz file from the ftp site. you are correct, it is not in a .pcap format.
By looking at the file in the text editor I can guess that the ITCH formatted message starts from column 14-15 onwards.
![bx_itch](https://user-images.githubusercontent.com/1273287/85981453-d769f300-ba01-11ea-8ff4-8ed5d588954d.png)

I will spend some time trying to find the file format used for these files and adapt my pcap reader to read this format.

Thanks for your help.

**Comment by jvirtanen** [comment]
@jahagirdar The file format is TotalView-ITCH inside BinaryFILE, see the [project documentation](https://github.com/paritytrading/nassau) for links to the specifications. I've written a [simple utility](https://github.com/jvirtanen/nasdaq-tools) that uses this project to read these files.
