### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by esanchezros** [paritytrading/nassau#94]
Hi,

Do you have an estimate on when a new version will be released to Maven Central?

Thanks
Ed

**Comment by jvirtanen** [comment]
Hi @esanchezros! 👋🏼  I don't have a set timeline, but I'm planning to release Foundation 1.0.0, Nassau 1.0.0, and Juncture 1.0.0 soon. I'm thinking of some minor API and implementation cleanups for Nassau 1.0.0.

**Comment by esanchezros** [comment]
Hi @jvirtanen, thanks for the update. We've started to use the library but saw some improvements from latest version `0.13.0`. Is it worth waiting for the new version or is the one available okay to use?
Thanks

**Comment by jvirtanen** [comment]
Glad to hear that, @esanchezros! 0.13.0 is fine to use, the changes for 1.0.0 will be small.
